// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUiAutomatorProcess(arg1) {
  return window['go']['main']['App']['CheckUiAutomatorProcess'](arg1);
}

export function CropAndSaveScreenshot(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CropAndSaveScreenshot'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetUIHierarchy(arg1) {
  return window['go']['main']['App']['GetUIHierarchy'](arg1);
}

export function KillProcess(arg1, arg2, arg3) {
  return window['go']['main']['App']['KillProcess'](arg1, arg2, arg3);
}

export function RebootDevice(arg1) {
  return window['go']['main']['App']['RebootDevice'](arg1);
}

export function TakeScreenshot(arg1) {
  return window['go']['main']['App']['TakeScreenshot'](arg1);
}
