// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adb} from '../models';

export function CheckUiAutomatorProcess(arg1:string):Promise<adb.ProcessInfo>;

export function CropAndSaveScreenshot(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:string):Promise<void>;

export function GetDevices():Promise<Array<adb.Device>>;

export function GetUIHierarchy(arg1:string):Promise<adb.UINode>;

export function KillProcess(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RebootDevice(arg1:string):Promise<void>;

export function TakeScreenshot(arg1:string):Promise<string>;
